require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/blacklists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Blacklist. As you add validations to Blacklist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Blacklist.create! valid_attributes
      get blacklists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      blacklist = Blacklist.create! valid_attributes
      get blacklist_url(blacklist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_blacklist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      blacklist = Blacklist.create! valid_attributes
      get edit_blacklist_url(blacklist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Blacklist" do
        expect {
          post blacklists_url, params: { blacklist: valid_attributes }
        }.to change(Blacklist, :count).by(1)
      end

      it "redirects to the created blacklist" do
        post blacklists_url, params: { blacklist: valid_attributes }
        expect(response).to redirect_to(blacklist_url(Blacklist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Blacklist" do
        expect {
          post blacklists_url, params: { blacklist: invalid_attributes }
        }.to change(Blacklist, :count).by(0)
      end

    
      it "renders a successful response (i.e. to display the 'new' template)" do
        post blacklists_url, params: { blacklist: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blacklist" do
        blacklist = Blacklist.create! valid_attributes
        patch blacklist_url(blacklist), params: { blacklist: new_attributes }
        blacklist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blacklist" do
        blacklist = Blacklist.create! valid_attributes
        patch blacklist_url(blacklist), params: { blacklist: new_attributes }
        blacklist.reload
        expect(response).to redirect_to(blacklist_url(blacklist))
      end
    end

    context "with invalid parameters" do
    
      it "renders a successful response (i.e. to display the 'edit' template)" do
        blacklist = Blacklist.create! valid_attributes
        patch blacklist_url(blacklist), params: { blacklist: invalid_attributes }
        expect(response).to be_successful
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blacklist" do
      blacklist = Blacklist.create! valid_attributes
      expect {
        delete blacklist_url(blacklist)
      }.to change(Blacklist, :count).by(-1)
    end

    it "redirects to the blacklists list" do
      blacklist = Blacklist.create! valid_attributes
      delete blacklist_url(blacklist)
      expect(response).to redirect_to(blacklists_url)
    end
  end
end
